# ============================================================================ #
#                                PROCESSING                                    #
# Summary:                                                                     #
# Instructions to use GWAMA:                                                   #
#  1. First install gwama (can be found on this directory).                    #
#  2. Create a .in file with the following lines:                              #
#       sc.txt                                                                 #
#       nn.txt                                                                 #
#       ng.txt                                                                 #
#     It will be read by GWAMA software to know which files it has to read.    #
#  3. Open command prompt in this directory                                    #
# Fixed effect method:                                                         #
#  4. Write in the command line the following:                                 #
# gwama -o D:/UK_Biobank_dataset/ver7/Sclerostin_vs_CVD_MR/Metaanalysis/Fixed_results/Fixed -qt
# Random effect method:                                                        #
#  5. Write in the command line the following:                                 #
# gwama -o D:/UK_Biobank_dataset/ver7/Sclerostin_vs_CVD_MR/Metaanalysis/Random_results/Random -qt -r
# Instructions to use METAL                                                    #
#  6. Click on metal.exe to open the command window.                           #
#  7. Write the following instructions:                                        #
#     SCHEME STDERR                                                            #
#     MARKER MARKERNAME                                                        #
#     ALLELELABELS EA NEA                                                      #
#     PVALUELABEL pval                                                         #
#     FREQLABEL EAF                                                            #
#     AVERAGEFREQ ON                                                           #
#     WEIGHTLABEL N                                                            #
#     STDERRLABEL SE                                                           #
#     EFFECTLABEL BETA                                                         #
#     PROCESS sc.txt                                                           #
#     PROCESS nn.txt                                                           #
#     PROCESS ng.txt                                                           #
#     ANALYZE                                                                  #
#    The file: METAANALYSIS1.TBL.info will contain the results                 #
#  6. Run this code to read the tables generated by GWAMA and METAL            #
# For the bidirectional codes -------------------------------------------------#
#  1. Go to: Sclerostin_vs_CVD_MR\SensitivityAnalysis\Bidirectiona and open a  #
#     command line                                                             #
#  2. Run the following command:                                               #
# gwama -o D:/UK_Biobank_dataset/ver7/Sclerostin_vs_CVD_MR/SensitivityAnalysis/Bidirectional/Fixed_results/Fixed -qt
#  3. Click on metal.exe to open the comman window and repeat the previous     #
#     instructions
# ============================================================================ #
rm(list = ls())
library(pacman)
pacman::p_load('tibble','dplyr','tidyverse','readr','here')

# Read GWAMA file --------------------------------------------------------------
# Read the output files
t1 <- as_tibble(read.delim(here("Metaanalysis","Fixed_results","Fixed.out"), sep = "\t"))
t2 <- as_tibble(read.delim(here("Metaanalysis","Random_results","Random.out"), sep = "\t"))
# Add SE column
t1 <- t1 %>%
  mutate(se = (beta-beta_95L)/1.96)
t2 <- t2 %>%
  mutate(se = (beta-beta_95L)/1.96)

# Save the results
write.csv(t1,here("Metaanalysis","Fixed_results","Fixed.csv"))
write.csv(t2,here("Metaanalysis","Random_results","Random.csv"))

# Read METAL file --------------------------------------------------------------
t3 <- as_tibble(read.delim(here("Metaanalysis","METAANALYSIS1.TBL"), sep = "\t"))

write.csv(t3,here("Metaanalysis","Fixed_results","Fixed_metal.csv"))

# Table to compare the results of both analysis
tab <- t1 %>%
  select("SNP" = "rs_number",
         "EA.fixed" = "reference_allele",
         "OA.fixed" = "other_allele",
         "Effect.fixed" = "beta",
         "pval.fixed" = "p.value",
         "se.fixed" = "se") %>%
  inner_join(t2 %>% 
               select("SNP" = "rs_number",
                      "EA.random" = "reference_allele",
                      "OA.random" = "other_allele",
                      "Effect.random" = "beta",
                      "pval.random" = "p.value",
                      "i2","q_statistic","n_samples",
                      "se.random" = "se"),
             by = "SNP") %>% 
  inner_join(t3 %>%
               select("SNP" = "MarkerName",
                      "EA.fixed.metal" = "Allele1",
                      "OA.fixed.metal" = "Allele2",
                      "Effect.fixed.metal" = "Effect",
                      "pval.fixed.metal" = "P.value",
                      "se.fixed.metal" = "StdErr"),
             by = "SNP") %>%
  left_join(read.delim(here("Metaanalysis","sc.txt")) %>% select("Pos","SNP" = "MARKERNAME"),
            by = "SNP") %>%
  filter(Pos <= 41836156+500000, Pos >= 41831099-500000) # SNPs in the SOST region
  

# Save the results
write.csv(tab,here("Metaanalysis","Fixed_vs_random.csv"))

